# Generated by Django 6.0 on 2025-12-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('dst_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('reconstruction_error', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
            ],
        ),
    ]
